drivers: power: supply: bq27z561: fix type specifier missing
drivers/power/supply/qcom/bq27z561.c:1247:9: error: type specifier missing, defaults to 'int' [-Werror,-Wimplicit-int]
        static last_time_ot = 0;
        ~~~~~~ ^
        int

Signed-off-by: Pulkit077 <pulkitagarwal2k1@gmail.com>